In [1]:
import numpy

In [3]:
n = numpy.arange(27)

In [4]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [6]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
m = numpy.asarray([[123,12,123,12,33],[],[]])

In [8]:
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [9]:
type(m)

numpy.ndarray

In [10]:
print(m)

[list([123, 12, 123, 12, 33]) list([]) list([])]


### OpenCV

In [2]:
import cv2

#### Reading an image in Gray Scale (<file_name>,0)

In [14]:
im_g = cv2.imread("smallgray.png",0)

In [15]:
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


#### Reading an image in BGR (<file_name>,1)

In [3]:
im_g = cv2.imread("smallgray.png",1)

In [4]:
print(im_g)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [5]:
cv2.imwrite("newsmallgray.png", im_g)

True